#!/bin/bash

# Itineraries - Railway Backend Deployment Script

echo "🚂 Railway Backend Deployment Guide"
echo "===================================="
echo ""
echo "Step 1: Login to Railway"
echo "------------------------"
echo "Run: railway login"
echo ""
echo "Step 2: Link to your project"
echo "----------------------------"
echo "Run: railway link"
echo "Select: rare-radiance"
echo ""
echo "Step 3: Set environment variables"
echo "---------------------------------"
echo "Run these commands one by one:"
echo ""
echo "railway variables set NODE_ENV=production"
echo "railway variables set PORT=8080"
echo "railway variables set JWT_SECRET=VsikozDe8/QU0DVBkVzsymzJz80tOVaqqoalkEik6zc="
echo "railway variables set DATABASE_PATH=../database/itineraries.db"
echo "railway variables set CLIENT_URL=https://itineraries-oycfj7tdg-scottrings-projects.vercel.app"
echo ""
echo "Step 4: Deploy"
echo "--------------"
echo "Run: railway up"
echo ""
echo "Step 5: Get your deployment URL"
echo "-------------------------------"
echo "Run: railway domain"
echo ""
echo "Step 6: Update Vercel frontend"
echo "------------------------------"
echo "Go to Vercel dashboard and set:"
echo "VITE_API_BASE_URL = https://YOUR-RAILWAY-URL/api"
echo ""
echo "==============================================="
echo "Or use the Railway dashboard at railway.app"
echo "==============================================="